//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SectionDemo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section_Table
    {
        public int primary_key { get; set; }
        public int section_num { get; set; }
        public string section_name { get; set; }
        public bool display_id { get; set; }
        public Nullable<int> sort_order { get; set; }
        public string open_label { get; set; }
        public string description { get; set; }
    }
}
